# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='inventory',
            field=models.BooleanField(default=False),
        ),
    ]
